// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SayHello() {
  return window['go']['backend']['Config']['SayHello']();
}

export function StartUp(arg1) {
  return window['go']['backend']['Config']['StartUp'](arg1);
}
