// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetConf() {
  return window['go']['main']['Config']['SetConf']();
}

export function SetOutDir() {
  return window['go']['main']['Config']['SetOutDir']();
}

export function WailsInit() {
  return window['go']['main']['Config']['WailsInit']();
}

export function Name() {
  return window['go']['main']['Config']['Name']();
}
