// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetConf():Promise<string>;

export function SetOutDir():Promise<string>;

export function WailsInit():Promise<Error>;

export function Name():Promise<Error>;
